### ISSUE TITLE
issue with one model

### ISSUE THREAD

**Issue by designinsist** [karbonn/Overlay-Bootstrap#5]
This plugin installed few month ago by me on a site and it was working super fine but few day ago its stopped working.

the model pop is working on only first div and on rest of the div this pop is not working. 

any issue ?

One more thing this issue is only in chrome and with chrome version "Version 45.0.2454.85 m".
I have tested in old version of chrome 43 it work fine.
so there is issue with this plug in.

please have a look and leave your kind feedback.
Thanks

**Comment by karbonn** [comment]
Hi,
I have checked on chrome 45, but i can't reproduce your problem. Can you give me an URL in order to check ?
Thanks :)

**Comment by designinsist** [comment]
thank for replying :)
https://www.andwolf.com/collections/collections/urban-heights/

here you can see the issue 

![image](https://cloud.githubusercontent.com/assets/10362590/9831423/90cd3872-5970-11e5-90d7-8799bac62fdd.png)

You need to do as i show in the above picture to see the issue. :)

**Comment by karbonn** [comment]
Hi,
Sorry for the late response!
I think i have solved your problem:
In your theme, in CSS file:
@media screen and (-webkit-min-device-pixel-ratio: 0) {
    .Red_Masonary > .col-md-4 {
        display: inline !important;
    }
Remove the displaying property, it will solve your case (i think)

**Comment by designinsist** [comment]
No if you do that then overlay start working on first column rather then working on all divs :)

**Comment by designinsist** [comment]
do you get my point :)

**Comment by karbonn** [comment]
Yup i try to understand why it's not working only on chrome 45 ^^

**Comment by designinsist** [comment]
now we are on same page. and if you disable what you suggest and check any browser of the world the result will be 100% and if you want to test then test it on chrome<45 .

**Comment by karbonn** [comment]
Hmm when you disabled the float property on .col-md-4 and the overflow property on .panel-body, it works

**Comment by karbonn** [comment]
Hum, when you disabled the previous inline property on 
.Red_Masonary > .col-md-4 {
display: inline !important;
}
AND the overfloiw property on .panel-body, it workds

**Comment by designinsist** [comment]
i try this already bro.
but when i did this this happen.

https://www.andwolf.com/browse-all/

open the link and go tho last images and hover your mouse then you will understand. i did this on this page using page id so that other site don't disturb.

**Comment by designinsist** [comment]
got my point ?

**Comment by karbonn** [comment]
Yup, i try to apply specific rules on last child

**Comment by karbonn** [comment]
.Red_Masonary > .col-md-4:last-child{
display:block;
}
It fix the problem but it also modify a little your design :(

**Comment by designinsist** [comment]
i know about this one too :P but let me find some thing better
:)

**Comment by designinsist** [comment]
I think you can mark this fixed I fixed it. thanks for your support.
this is really a good plug in.
I like it. 
:+1:
